mode: production
media_root: media
media_url: "http://web.media.mit.edu/~rspeer/media"
deploy_root: deploy
base_url: "http://web.media.mit.edu/~rspeer"
template: hyde.ext.jinja2
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
aggregators:
meta:
    extends: base.html
    charset: utf-8
    author: Rob Speer
    default_block: markdown
sorter:
    date:
        attr: meta.created
        filters:
            meta.published: True
        reverse: True

